name: docker

on: [push]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: build ppt docker image
  #       run: docker build . --file dockerfiles/nodeppt/Dockerfile --tag nodeppt:$(date +%s)

  build-push-nodeppt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/nodeppt
          file: dockerfiles/nodeppt/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: driaan/nodeppt:latest

  build-push-jupyterhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/jupyterhub
          file: dockerfiles/jupyterhub/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: driaan/jupyterhub:latest
